version: '3'

services:
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: natacodedev
      MONGO_INITDB_ROOT_PASSWORD: 63he9h33AOM30j.sskeDB
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
    driver: local
