export const TAGS = [
  { label: 'Android', value: 'Android' },
  { label: 'iOS', value: 'iOS' },
  { label: 'Node.JS', value: 'Node.JS' },
  { label: 'Back-end', value: 'Back-end' },
  { label: 'Golang', value: 'Golang' },
  { label: 'JavaScript', value: 'JavaScript' },
  { label: 'Java', value: 'Java' },
  { label: 'Elixir', value: 'Elixir' },
  { label: 'C#', value: 'C#' },
  { label: 'PHP', value: 'PHP' },
  { label: 'Angular', value: 'Angular' },
  { label: 'React', value: 'React' },
  { label: 'React Native', value: 'React Native' },
  { label: 'Python', value: 'Python' },
  { label: '.NET', value: '.NET' },
  { label: 'Flutter', value: 'Flutter' },
  { label: 'Kotlin', value: 'Kotlin' },
  { label: 'Clojure', value: 'Clojure' },
  { label: 'DevOps', value: 'DevOps' },
  { label: 'Docker', value: 'Docker' },
  { label: 'AWS', value: 'AWS' },
  { label: 'GCloud', value: 'GCloud' },
  { label: 'Azure', value: 'Azure' },
  { label: 'K8S', value: 'K8S' },
  { label: 'Scrum', value: 'Scrum' },
  { label: 'Kanban', value: 'Kanban' },
  { label: 'LEAN', value: 'LEAN' },
  { label: 'Startups', value: 'Startups' },
  { label: 'Fintechs', value: 'Fintechs' },
  { label: 'Data Science', value: 'Data Science' },
  { label: 'Data Analysis', value: 'Data Analysis' },
  { label: 'Data Engineering', value: 'Data Engineering' },
  { label: 'Machine Learn', value: 'Machine Learn' },
  { label: 'Deep Learning', value: 'Deep Learning' },
  { label: 'Redes Neurais', value: 'Redes Neurais' },
  { label: 'Tensor Flow', value: 'Tensor Flow' },
  { label: 'Pytorch', value: 'Pytorch' },
  { label: 'LGPD', value: 'LGPD' },
  { label: 'OWASP', value: 'OWASP' },
  { label: 'PCI', value: 'PCI' },
  { label: 'Operation Systems', value: 'Operation Systems' },
  { label: 'Hardware', value: 'Hardware' },
  { label: 'UX', value: 'UX' },
  { label: 'UI', value: 'UI' },
  { label: 'Game design', value: 'Game design' },
];
